### ISSUE TITLE
Cannot Complied when hyphen in our path

### ISSUE THREAD

**Issue by uqutub** [firebase/bolt#92]
when compiles

type Test1 {
 "first-name": String;
}

path /team-member2 is Test1 {
	read() = true;
	write() = true;
}

error: 
bolt:5:1: Expected comment, end of input, function definition, path statement, type statement or whitespace but "p" found.

**Comment by uqutub** [comment]
path /'test-1'/abc {
	read()= auth != null;
}

//after compiles err:

bolt:1:1: Expected comment, end of input, function definition, path statement, type statement or whitespace but "p" found.

even not compiles with quotes;

path /'test1'/abc {
	read()= auth != null;
}

**Comment by mckoss** [comment]
Fixed by 6fca4e19be602580f70d4abd862b517cc0b8549f

Note that you don't need quotes to add a hyphen to the path (after this fix).

**Comment by uqutub** [comment]
path /test-1/abc {
read()= auth != null;
}

Still facing same error: (using Firebase Bolt v0.5.0)

bolt:1:1: Expected comment, end of input, function definition, path statement, type statement or whitespace but "p" found.

**Comment by mm-gmbd** [comment]
@mckoss, please re-open as the bug still persists. Also, I'm getting the same error even without hyphens in the path.

    path /path/$wildcard/data {
      read():   true
      write():  false
    }

Generates the error:

    bolt:1:1: Expected comment, end of input function definition, path statement, type statement or whitespace but "p" found.

**Comment by mckoss** [comment]
I just released Bolt 0.6.0 which allows for hyphens in path statements, now.
